[chore] update node.js.yml

diff --git a/.github/workflows/node.js.yml b/.github/workflows/node.js.yml
--- a/.github/workflows/node.js.yml
+++ b/.github/workflows/node.js.yml
@@ -32,10 +32,15 @@ jobs:
     
     - name: Test Output
       id: test-results
-      run: npm run test:json
+      run: npm run test:json            # run tests (configured to use jest-junit reporter)
+    - uses: actions/upload-artifact@v2  # upload test results
+      if: success() || failure()        # run this step even if previous step failed
+      with:
+        name: test-results
+        path: jest-junit.xml
 
-    - name: Test Stats
-      run: echo "Stats are ${{ fromJSON( steps.test-results.outputs.json ).stats }}"
+    - name: Test Conclusion
+      run: echo "Stats are ${{ fromJSON( steps.test-results.outputs.json ).conclusion }}"
 
     - name: Set badge color
       shell: bash
